In [6]:
#pandas
Pandas is a Python library used to analyze and manipulate data in tables.

SyntaxError: invalid syntax (3869205877.py, line 2)

In [ ]:
pip install pandas

Requirement already satisfied: pandas in c:\Users\SURFACE\Desktop\pyhton\HARSH\Lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=2.3.3 in c:\Users\SURFACE\Desktop\pyhton\HARSH\Lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\Users\SURFACE\Desktop\pyhton\HARSH\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\SURFACE\Desktop\pyhton\HARSH\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in c:\Users\SURFACE\Desktop\pyhton\HARSH\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [7]:
import os
import numpy as np 
import pandas as pd

In [8]:
df= pd.read_csv(r"C:\Users\SURFACE\Desktop\pyhton\num py\pandas.ipynb\Used_Bikes (2).csv")
df

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
32643,Hero Passion Pro 100cc,39000.0,Delhi,22000.0,First Owner,4.0,100.0,Hero
32644,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS
32645,Bajaj Avenger Street 220,60000.0,Delhi,20373.0,First Owner,6.0,220.0,Bajaj
32646,Hero Super Splendor 125cc,15600.0,Jaipur,84186.0,First Owner,16.0,125.0,Hero
32647,Bajaj Pulsar 150cc,22000.0,Pune,60857.0,First Owner,13.0,150.0,Bajaj

In [ ]:
df.head()   # it is used for first five rows can be output.

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha

In [ ]:
df.head(10)#it is used 10 rows can be in print

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
5,Yamaha FZs 150cc,53499.0,Delhi,25000.0,First Owner,6.0,150.0,Yamaha
6,Honda CB Hornet 160R ABS DLX,85000.0,Delhi,8200.0,First Owner,3.0,160.0,Honda
7,Hero Splendor Plus Self Alloy 100cc,45000.0,Delhi,12645.0,First Owner,3.0,100.0,Hero
8,Royal Enfield Thunderbird X 350cc,145000.0,Bangalore,9190.0,First Owner,3.0,350.0,Royal Enfield
9,Royal Enfield Classic Desert Storm 500cc,88000.0,Delhi,19000.0,Second Owner,7.0,500.0,Royal Enfield

In [ ]:
df.tail()#it is used for last five output in rows can be print

,bike_name,price,city,kms_driven,owner,age,power,brand
32643,Hero Passion Pro 100cc,39000.0,Delhi,22000.0,First Owner,4.0,100.0,Hero
32644,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS
32645,Bajaj Avenger Street 220,60000.0,Delhi,20373.0,First Owner,6.0,220.0,Bajaj
32646,Hero Super Splendor 125cc,15600.0,Jaipur,84186.0,First Owner,16.0,125.0,Hero
32647,Bajaj Pulsar 150cc,22000.0,Pune,60857.0,First Owner,13.0,150.0,Bajaj

In [ ]:
df.tail(10)

,bike_name,price,city,kms_driven,owner,age,power,brand
32638,Yamaha Fazer 25 250cc,123000.0,Kadapa,14500.0,First Owner,4.0,250.0,Yamaha
32639,Royal Enfield Classic 350cc,95500.0,Delhi,18000.0,First Owner,8.0,350.0,Royal Enfield
32640,Hero Passion Pro 100cc,32000.0,Delhi,12000.0,First Owner,6.0,100.0,Hero
32641,Bajaj Avenger 220cc,41000.0,Delhi,20245.0,Second Owner,11.0,220.0,Bajaj
32642,Hero Passion 100cc,15000.0,Perumbavoor,35000.0,Second Owner,19.0,100.0,Hero
32643,Hero Passion Pro 100cc,39000.0,Delhi,22000.0,First Owner,4.0,100.0,Hero
32644,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS
32645,Bajaj Avenger Street 220,60000.0,Delhi,20373.0,First Owner,6.0,220.0,Bajaj
32646,Hero Super Splendor 125cc,15600.0,Jaipur,84186.0,First Owner,16.0,125.0,Hero
32647,Bajaj Pulsar 150cc,22000.0,Pune,60857.0,First Owner,13.0,150.0,Bajaj

In [ ]:
df.info()
# it is used for information of any table

<class 'pandas.DataFrame'>
RangeIndex: 32648 entries, 0 to 32647
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   bike_name   32648 non-null  str
 1   price       32648 non-null  float64
 2   city        32648 non-null  str
 3   kms_driven  32648 non-null  float64
 4   owner       32648 non-null  str
 5   age         32648 non-null  float64
 6   power       32648 non-null  float64
 7   brand       32648 non-null  str
dtypes: float64(4), str(4)
memory usage: 2.0 MB

In [ ]:
df.columns    
# it is used for what columns can be used in tables.

Index(['bike_name', 'price', 'city', 'kms_driven', 'owner', 'age', 'power',
       'brand'],
      dtype='str')

In [ ]:
df['brand'] #it used for access any columns.
df[['brand']] #it is used for acess any column in a tabular form

               brand
0                TVS
1      Royal Enfield
2            Triumph
3                TVS
4             Yamaha
...              ...
32643           Hero
32644            TVS
32645          Bajaj
32646           Hero
32647          Bajaj

[32648 rows x 1 columns]

In [ ]:
df[['brand','owner','bike_name']]

               brand        owner                             bike_name
0                TVS  First Owner    TVS Star City Plus Dual Tone 110cc
1      Royal Enfield  First Owner           Royal Enfield Classic 350cc
2            Triumph  First Owner                  Triumph Daytona 675R
3                TVS  First Owner                  TVS Apache RTR 180cc
4             Yamaha  First Owner  Yamaha FZ S V 2.0 150cc-Ltd. Edition
...              ...          ...                                   ...
32643           Hero  First Owner                Hero Passion Pro 100cc
32644            TVS  First Owner                  TVS Apache RTR 180cc
32645          Bajaj  First Owner              Bajaj Avenger Street 220
32646           Hero  First Owner             Hero Super Splendor 125cc
32647          Bajaj  First Owner                    Bajaj Pulsar 150cc

[32648 rows x 3 columns]

In [ ]:
# df["brand"].unique()

<StringArray>
[            'TVS',   'Royal Enfield',         'Triumph',          'Yamaha',
           'Honda',            'Hero',           'Bajaj',          'Suzuki',
         'Benelli',             'KTM',        'Mahindra',        'Kawasaki',
          'Ducati',         'Hyosung', 'Harley-Davidson',            'Jawa',
             'BMW',          'Indian',         'Rajdoot',             'LML',
           'Yezdi',              'MV',           'Ideal']
Length: 23, dtype: str

In [ ]:
# df["owner"].unique()

<StringArray>
['First Owner', 'Second Owner', 'Third Owner', 'Fourth Owner Or More']
Length: 4, dtype: str

In [ ]:
# df['city'].unique()

<StringArray>
[   'Ahmedabad',        'Delhi',    'Bangalore',       'Mumbai',
       'Kalyan',    'Faridabad',       'Mettur',    'Hyderabad',
      'Kaithal',      'Gurgaon',
 ...
  'Bhubaneswar',      'Raiganj', 'Bhilai Nagar',       'Baloda',
     'Anantnag',   'Berhampore',      'Silvasa',       'Hospet',
        'Palai',        'Sidhi']
Length: 443, dtype: str

In [ ]:
# df["brand"].nunique()  # it is used to check a unique value of any table

23

In [ ]:
# df["brand"].value_counts() # it is used for value count of any brand and number of brand bike

brand
Bajaj              11213
Hero                6368
Royal Enfield       4178
Yamaha              3916
Honda               2108
Suzuki              1464
TVS                 1247
KTM                 1077
Harley-Davidson      737
Kawasaki              79
Hyosung               64
Benelli               56
Mahindra              55
Triumph               26
Ducati                22
BMW                   16
Jawa                  10
MV                     4
Indian                 3
Ideal                  2
Rajdoot                1
LML                    1
Yezdi                  1
Name: count, dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(25324)

In [ ]:
df.drop_duplicates(inplace=True)  # drop the duplicated value and inplace true

In [ ]:
df.isnull().sum()

bike_name     0
price         0
city          0
kms_driven    0
owner         0
age           0
power         0
brand         0
dtype: int64

In [ ]:
# y=mx+c  # linear regression

# df.info()

<class 'pandas.DataFrame'>
Index: 7316 entries, 0 to 9372
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   bike_name   7316 non-null   str
 1   price       7316 non-null   float64
 2   kms_driven  7316 non-null   float64
 3   owner       7316 non-null   int64
 4   age         7316 non-null   float64
 5   power       7316 non-null   float64
 6   brand       7316 non-null   str
dtypes: float64(4), int64(1), str(2)
memory usage: 457.2 KB

In [ ]:
# df["owner"].unique()

<StringArray>
['First Owner', 'Second Owner', 'Third Owner', 'Fourth Owner Or More']
Length: 4, dtype: str

In [ ]:
# owner_dict={
#     'First Owner':1, 'Second Owner':2, 'Third Owner':3, 'Fourth Owner Or More':4
# }

In [ ]:
# df["owner"]=df["owner"].map(owner_dict)

In [ ]:
df

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,1,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,1,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,1,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,1,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,1,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
32643,Hero Passion Pro 100cc,39000.0,Delhi,22000.0,1,4.0,100.0,Hero
32644,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,1,9.0,180.0,TVS
32645,Bajaj Avenger Street 220,60000.0,Delhi,20373.0,1,6.0,220.0,Bajaj
32646,Hero Super Splendor 125cc,15600.0,Jaipur,84186.0,1,16.0,125.0,Hero
32647,Bajaj Pulsar 150cc,22000.0,Pune,60857.0,1,13.0,150.0,Bajaj

In [ ]:
# df.drop("city", axis=1,inplace=True)

In [ ]:
# df['brand'].unique()

<StringArray>
[            'TVS',   'Royal Enfield',         'Triumph',          'Yamaha',
           'Honda',            'Hero',           'Bajaj',          'Suzuki',
         'Benelli',             'KTM',        'Mahindra',        'Kawasaki',
          'Ducati',         'Hyosung', 'Harley-Davidson',            'Jawa',
             'BMW',          'Indian',         'Rajdoot',             'LML',
           'Yezdi',              'MV',           'Ideal']
Length: 23, dtype: str

In [ ]:
# brand_dict={   'TVS':1,   'Royal Enfield':2,         'Triumph':3,          'Yamaha':4,
#            'Honda':5,            'Hero':6,           'Bajaj':7,          'Suzuki':8,
#          'Benelli':9,             'KTM':10,        'Mahindra':11,        'Kawasaki':12,
#           'Ducati':13,         'Hyosung':14, 'Harley-Davidson':15,            'Jawa':16,
#          'BMW':17,          'Indian':18,         'Rajdoot':19,             'LML':20,
#            'Yezdi':21,              'MV':22,           'Ideal':23}

In [ ]:
# df['brand']=df['brand'].map(brand_dict)

In [ ]:
# df

,bike_name,price,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,17654.0,First Owner,3.0,110.0,1
1,Royal Enfield Classic 350cc,119900.0,11000.0,First Owner,4.0,350.0,2
2,Triumph Daytona 675R,600000.0,110.0,First Owner,8.0,675.0,3
3,TVS Apache RTR 180cc,65000.0,16329.0,First Owner,4.0,180.0,1
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,10000.0,First Owner,3.0,150.0,4
...,...,...,...,...,...,...,...
32643,Hero Passion Pro 100cc,39000.0,22000.0,First Owner,4.0,100.0,6
32644,TVS Apache RTR 180cc,30000.0,6639.0,First Owner,9.0,180.0,1
32645,Bajaj Avenger Street 220,60000.0,20373.0,First Owner,6.0,220.0,7
32646,Hero Super Splendor 125cc,15600.0,84186.0,First Owner,16.0,125.0,6
32647,Bajaj Pulsar 150cc,22000.0,60857.0,First Owner,13.0,150.0,7

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 32648 entries, 0 to 32647
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   bike_name   32648 non-null  str
 1   price       32648 non-null  float64
 2   kms_driven  32648 non-null  float64
 3   owner       32648 non-null  str
 4   age         32648 non-null  float64
 5   power       32648 non-null  float64
 6   brand       32648 non-null  int64
dtypes: float64(4), int64(1), str(2)
memory usage: 1.7 MB

In [ ]:
obj_val=df.select_dtypes(include='O')

C:\Users\SURFACE\AppData\Local\Temp\ipykernel_16348\3000755879.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  obj_val=df.select_dtypes(include='O')

In [ ]:
complete_data=pd.concat([obj_val,num_val],axis=1)

NameError: name 'num_val' is not defined

In [ ]:
df.complete_data

NameError: name 'df' is not defined

In [9]:
df[df['brand']=='TVS']

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
52,TVS Apache RTR 160cc,60000.0,Mumbai,30000.0,First Owner,5.0,160.0,TVS
114,TVS Apache RTR 160 4V Disc,69900.0,Delhi,8700.0,First Owner,3.0,160.0,TVS
130,TVS Phoenix Disc 125cc,21500.0,Barasat,10500.0,First Owner,5.0,125.0,TVS
...,...,...,...,...,...,...,...,...
32549,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS
32568,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS
32587,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS
32606,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS
32644,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS

In [ ]:
# TVS_brand=df[df['brand']=='TVS']

In [ ]:
# TVS_FIRST=TVS_brand

In [21]:
royal_enfield=df[df['brand']=="Royal Enfield"]